vim.keymap.set('i', '<Tab>', function () return vim.fn['codeium#Accept']() end, { expr = true })
vim.keymap.set('i', '<leader>]', function() return vim.fn['codeium#CycleCompletions'](1) end, { expr = true })
vim.keymap.set('i', '<leader>[', function() return vim.fn['codeium#CycleCompletions'](-1) end, { expr = true })
vim.keymap.set('i', '<leader>Bslash', function() return vim.fn['codeium#Clear']() end, { expr = true })
vim.keymap.set('i', '<leader>/', function() return vim.fn['codeium#Complete']() end, { expr = true })
